2024-11-23 07:47:48,026 - INFO - Starting astronomical data analysis
2024-11-23 07:47:48,026 - INFO - Loading data from ../../astrCsv.csv
2024-11-23 07:47:51,673 - INFO - Calculating distance and motion vectors
2024-11-23 07:47:52,318 - ERROR - Error during analysis: 'st_radv'
Traceback (most recent call last):
  File "F:\MTech_IIITD\Semester 1\Machine Learning\Projects\Astronomical Svent Simulator\pyENv\Lib\site-packages\pandas\core\indexes\base.py", line 3805, in get_loc
    return self._engine.get_loc(casted_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 196, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\\_libs\\hashtable_class_helper.pxi", line 7081, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\\_libs\\hashtable_class_helper.pxi", line 7089, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'st_radv'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "F:\MTech_IIITD\Semester 1\Machine Learning\Projects\Astronomical Svent Simulator\PythonFiles\EDA_Projection\main.py", line 44, in run_analysis
    data = calculate_distance_and_motion_vectors(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\MTech_IIITD\Semester 1\Machine Learning\Projects\Astronomical Svent Simulator\PythonFiles\EDA_Projection\Visualize_path.py", line 13, in calculate_distance_and_motion_vectors
    motion_Radial = data['st_radv']
                    ~~~~^^^^^^^^^^^
  File "F:\MTech_IIITD\Semester 1\Machine Learning\Projects\Astronomical Svent Simulator\pyENv\Lib\site-packages\pandas\core\frame.py", line 4102, in __getitem__
    indexer = self.columns.get_loc(key)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\MTech_IIITD\Semester 1\Machine Learning\Projects\Astronomical Svent Simulator\pyENv\Lib\site-packages\pandas\core\indexes\base.py", line 3812, in get_loc
    raise KeyError(key) from err
KeyError: 'st_radv'
2024-11-23 07:47:52,407 - ERROR - Application failed: 'st_radv'
